[package]
name = "diesel_mocks"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Taryn Hill <taryn@phrohdoh.com>"]
edition = "2018"

[dependencies]
diesel = { git = "https://github.com/diesel-rs/diesel", rev = "9edd8a", features = ["sqlite"] }
dotenv = "0.15"

[lib]
doc = false
